services:
  bot:
    container_name: toilet
    image: ghcr.io/greek/toilet-bot:master
    networks:
      - tnet
    environment:
      - DISCORD_PREFIX=${DISCORD_PREFIX}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DATABASE_DSN=${DATABASE_DSN:-postgres://postgres:postgres@localhost:5432/app}
      - MONGO_DB=${MONGO_DB:-mongodb://root:toilet@database:27017/}${MONGO_NAME:-toilet}
      - MONGO_NAME=${MONGO_NAME:-toilet}
      - REDIS_URL=${REDIS_URL:-redis://default:@redis:6379}
      - LAST_FM_KEY=${LAST_FM_KEY}
      - LAST_FM_SECRET=${LAST_FM_SECRET}
    volumes:
      - ./.env:/usr/src/app/.env:rw
      - ./config.json:/usr/src/app/config.json
    depends_on:
      - database
      - redis
    
  # Redis instance used for keeping track of temporary & permanent events.
  # Not exposed to the internet.
  redis:
    container_name: redis
    image: redis:7.0.4
    networks:
      - tnet
    restart: always
    command: "redis-server /usr/local/etc/redis/redis.conf --save 20 1 --loglevel warning"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  # Database
  database:
    container_name: database
    image: postgres
    networks:
      - tnet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # MongoDB database to store permenant pieces of data.
  # Exposed to internet, port ?
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toilet

networks:
  tnet:

volumes:
  toilet:
  